#!/usr/bin/env bash
# Update package index
sudo apt update

# Install nginx
sudo apt install -y nginx   # The -y flag automatically answers yes to prompts

# Check nginx service status
sudo service nginx status

# Start nginx service
sudo service nginx start

# Check nginx service status again
sudo service nginx status

# Ensure nginx listens on port 80 of all IPv4 IPs
sudo netstat -tuln | grep ':80'
